### ISSUE TITLE
Add prerequisites for graph view

### ISSUE THREAD

**Issue by liuj-42** [anderm18/HASSPathways#47]
current idea is to have a modal/alert that pops up whenever a user selects a course with a prerequisites and to have something like another course modifier that indicates whether or not the course has a prerequisites or not.
## tasks
- [x] get prerequisites to actually show up somewhere
- [x] add prerequisites to course modifier component
    - [x] add a chip to the component
    - [x] get it integrated with the current view of course cards
- [x] alert the user whenever the course they select has prerequisites
    - [x] add to the onclick event that happens whenever a course card is clicked
    - [x] figure out how to make modals/alerts/notifications with vue(tify) 
    ~~if we have a modal maybe make it work so it only shows up once every x seconds for a specific class~~

- [x] have the courses with pre-reqs show up on the my pathways page
    - [x] either highlight the course in the display or something and tell the user to look at the course or have the pre requisites show up somewhere on the my pathways page

**Comment by liuj-42** [comment]
https://github.com/stanko-arbutina/arrow-line
probably will help with this
